### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by robb1e** [pivotalexperimental/style-guide#2]
I've followed the instructions, but get the following error when I boot:

uninitialized constant Rails::Engine::ActionDispatch

**Comment by ohrite** [comment]
I'm going to be updating the readme today, but in the meantime can you provide a stack trace and Ruby/gem versions? (Actually those'll ride along with a stack trace, won't they?)

**Comment by ohrite** [comment]
Sounds like you got this started on your app!
