### ISSUE TITLE
Can't render inside style guide partial

### ISSUE THREAD

**Issue by robb1e** [pivotalexperimental/style-guide#3]
I've successfully created a new partial inside the style guide but I want to render a partial from inside my application. It fails saying the method 'render' is unavailable. 

The code loads the partial as a file, I guess the view helpers aren't available. Can you load differently so I can access my partials?

**Comment by ohrite** [comment]
Aha, this is due to Tilt not being Rails (https://github.com/pivotalexperimental/style-guide/blob/master/lib/style_guide/partial.rb#L63), got it.

**Comment by ohrite** [comment]
Addressed in dddc7a2ff04c3d611b0580aa63a62b2d7de663fd
