### ISSUE TITLE
Overriding Layout

### ISSUE THREAD

**Issue by brendastorer** [pivotalexperimental/style-guide#7]
Hi,

I am trying to add in partials that are used within my site's layout that are not included in the style guide's layout. Is there a way to add that in?

Thanks!

**Comment by ohrite** [comment]
Do you mean that you'd like to add other directories to the things that
style guide is rendering?

**Comment by brendastorer** [comment]
We have a partial that loads some javascript globals that our application.js requires in the head and without them, all of the javascript are breaking in the style guide.

**Comment by ohrite** [comment]
That's an interesting idea. I think this might be a feature at some point,
but the style guide as it stands today and for the foreseeable future only
includes `app/assets/javascripts/application.js`.

Is there a way you could move requiring your globals into application.js?
