### ISSUE TITLE
Removing default examples

### ISSUE THREAD

**Issue by brendastorer** [pivotalexperimental/style-guide#8]
Hi,

I would like to remove the default tabs from the navigation. How do I do that?

Thanks!

**Comment by ohrite** [comment]
In `config/application.rb` there should be a line that looks like this: https://github.com/pivotalexperimental/style-guide/blob/master/spec/dummy/config/application.rb#L29

Change the `<<` to `= [Rails.root.join(…)]` and the style guide should just show the local examples!

**Comment by brendastorer** [comment]
That worked perfectly. Thank you!

**Comment by ohrite** [comment]
@brendastorer i'm going to close this out, since it seems like you've got it all squared away. also, wow time flies when i'm not actively maintaining! :calendar:
